name: Test
on: push

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          sudo apt-get update && sudo apt-get install -y flex bison
      - name: Build
        run: |
          make
      - name: Test
        run: |
          timeout 30s ./gradeMe.sh
